Implemented On This Day API
timeanddate/libtad-jvm pull request #2
Opened 2021-07-12 07:35 UTC by danielalvsaaker

- Constructor set to private until the API is released.

2021-08-12 08:22 UTC, ninjacato requested changes
Looks good! I've added suggestions for some improvements to future-proof the naming of some classes

2021-08-12 08:22 UTC, ninjacato commented on TimeAndDate/main/com/timeanddate/services/dataTypes/onthisday/EventType.java
> +public enum EventType {
I can imagine there may be other kinds of Events from other services so I suggest renaming this to OTDEventType to make a distinction.

2021-08-12 08:22 UTC, ninjacato commented on TimeAndDate/main/com/timeanddate/services/common/StringUtils.java
> +	public static EventTuple resolveEventTypes(IPredicate<EventType> predicate) {
Since this is OTD specific I would rename it to resolveOTDEventType and OTDEventTuple. When we launch some of the next APIs there will be other types of events (tidal, etc.)

2021-08-16 09:24 UTC, danielalvsaaker commented on TimeAndDate/main/com/timeanddate/services/BusinessDuration.java
> +					duration.Period = com.timeanddate.services.dataTypes.businessdays.Period.fromNode(node);
I reverted this, because the compiler can't infer if Period refers to the Period class or the Period variable owned by this class.

2021-08-16 09:26 UTC, danielalvsaaker commented on TimeAndDate/main/com/timeanddate/services/BusinessDuration.java
> +					duration.Period = com.timeanddate.services.dataTypes.businessdays.Period.fromNode(node);
The result is a single ugly line in the source, but at least the variable is clear from a user's perspective.

2021-08-22 19:01 UTC, ninjacato approved these changes

2021-08-22 19:01 UTC, merged